### ISSUE TITLE
LevelRenderer and renderer package cannot be found

### ISSUE THREAD

**Issue by badcodebuilder** [vampire-studios/Customized-Astral-Body#3]
https://github.com/vampire-studios/Customized-Astral-Body/blob/d19096b81e845c5efdecfb11373e28634e828bc5/src/main/java/io/github/vampirestudios/cab/mixins/client/WorldRendererMixin.java#L21

This class cannot be found in Minecraft 1.18.2, Maybe it has been changed to `WorldRenderer`

https://github.com/vampire-studios/Customized-Astral-Body/blob/d19096b81e845c5efdecfb11373e28634e828bc5/src/main/java/io/github/vampirestudios/cab/mixins/client/WorldRendererMixin.java#L12

Package `net.minecraft.client.renderer.*` cannot be found nether, maybe it has be renamed as `net.minecraft.client.render`

**Comment by oliviathevampire** [comment]
This mod is made using Mojang-mappings so WorldRenderer is not a name for it. You're probably using yarn or quilt mappings. We've not updated this mod yet as we've not needed it.

**Comment by badcodebuilder** [comment]
Sorry for not noticing your reply😥, I built a new SkyRenderer with Fabric API, although it is being developed. But anyway, thanks for this repo and your reply, and I will close this issue.
